### ISSUE TITLE
Influx 2.0.X

### ISSUE THREAD

**Issue by davidwuest** [hedderich/influxdb-banktool#4]
Does this script work with InfluxDB 2.0.X . I have problems getting it to work with a token based authentication.

**Comment by davidwuest** [comment]
I'm keep getting the following error with correct credentials supplied:
Traceback (most recent call last):
  File "/usr/local/bin/influxdb-banktool", line 11, in <module>
    load_entry_point('influxdb-banktool==0.1.0', 'console_scripts', 'influxdb-banktool')()
  File "/usr/local/lib/python3.8/dist-packages/influxdb_banktool/main.py", line 17, in main
    rs = next(client.query(query).get_points())
  File "/usr/local/lib/python3.8/dist-packages/influxdb/client.py", line 521, in query
    response = self.request(
  File "/usr/local/lib/python3.8/dist-packages/influxdb/client.py", line 378, in request
    raise InfluxDBClientError(err_msg, response.status_code)
influxdb.exceptions.InfluxDBClientError: 401: {"code":"unauthorized","message":"Unauthorized"}

Any ideas ?

influxDB 2.0.X
